#!/bin/env bash

# This script needs to be executed at the beginning bevor law can be used

####### helper functions and variables #######
add_to_path() {
    [ -n "$1" ] && export PATH="$1:$PATH"
}
add_to_pythonpath() {
    [ -n "$1" ] && export PYTHONPATH="$1:$PYTHONPATH"
}

# get the dir path the script is in regardless if bash or zsh is used (needs to be dynamic as this is also executed on remote (htcondor) nodes)
BASE_DIR=$(dirname "$(readlink -f -- ${BASH_SOURCE:-$0})")
# Path where law should stores index files (generated by `law index`)
LAW_HOME="$BASE_DIR/.law_tmp"
# path to law config 
# (see https://law.readthedocs.io/en/stable/config.html#configuration-file-resolution-order)
LAW_CONFIG_FILE=$BASE_DIR/law.cfg
export BASE_DIR LAW_HOME LAW_CONFIG_FILE

####### setup law and luigi #######
# add law and luigi to the path & python path
add_to_pythonpath "$BASE_DIR/luigi"
add_to_pythonpath "$BASE_DIR/law"

add_to_path "$BASE_DIR/luigi/bin"
add_to_path "$BASE_DIR/law/bin"

# setup law command completion
source "$(law completion)"

# index and print law tasks
law index --verbose